### ISSUE TITLE
Server pulls the commit in question

### ISSUE THREAD

**Issue by Glassar** [DD2480-group8-VT24/DD2480-Assignment-2-CI#4]
- git clone "repo"
- git checkout "commit id"

**Comment by Atheer2104** [comment]
> * git clone "repo"
> * git checkout "commit id"

Here it's actually not needed to checkout the "commit id" since in the grading they always talk about that one has to check out the branch from where the push event came from

**Comment by Glassar** [comment]
Yes, need the full 40 letter SHA

tors 8 feb. 2024 kl. 09:50 skrev Atheer ***@***.***>:
